version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d67osdvgi27c73a23a0g-a:5432/retaildb_uskm?sslmode=require
      SPRING_DATASOURCE_USERNAME: retaildb_uskm_user
      SPRING_DATASOURCE_PASSWORD: hRifZEt1NBtty2vc3XkE17fb9vz6veK3
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      SPRING_JACKSON_PROPERTY_NAMING_STRATEGY: SNAKE_CASE
    networks:
      - springboot-net

networks:
  springboot-net:
    driver: bridge
