version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d6u8dp75r7bs73fsn40g-a:5432/retaildb_txwm?sslmode=require
      SPRING_DATASOURCE_USERNAME: retaildb_txwm_user
      SPRING_DATASOURCE_PASSWORD: HabWiwNFuiSJOUnaZj5LYk7u9ArUMpYZ
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      SPRING_JACKSON_PROPERTY_NAMING_STRATEGY: SNAKE_CASE
    networks:
      - springboot-net

networks:
  springboot-net:
    driver: bridge
