version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://retaildb_0dlp_user:3MZl8vcXwErw6Uz9qtY92yeAGi3XeVeq@dpg-d4strjmr433s73cld640-a/retaildb_0dlp?sslmode=require
      SPRING_DATASOURCE_USERNAME: retaildb_0dlp_user
      SPRING_DATASOURCE_PASSWORD: 3MZl8vcXwErw6Uz9qtY92yeAGi3XeVeq
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      SPRING_JACKSON_PROPERTY_NAMING_STRATEGY: SNAKE_CASE
    networks:
      - springboot-net

networks:
  springboot-net:
    driver: bridge
