spring.application.name=OnlineRetailManagement

spring.datasource.url=jdbc:postgresql://dpg-d6u8dp75r7bs73fsn40g-a:5432/retaildb_txwm?sslmode=require
spring.datasource.username=retaildb_txwm_user
spring.datasource.password=HabWiwNFuiSJOUnaZj5LYk7u9ArUMpYZ

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jackson.property-naming-strategy=SNAKE_CASE
